### ISSUE TITLE
#1. test

### ISSUE THREAD

**Issue by haruharuganda** [gnims-project/GNIMS-frontend#1]
test용 Issues입니다.

**Comment by AngelaChaejung** [comment]
test 확인했습니다

**Comment by AngelaChaejung** [comment]
`function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}` 
이 코드 어떤가요? App.js입니다

**Comment by AngelaChaejung** [comment]
`function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}`
